iproute2: Fix typo in get_prefix_1()
Fixes a typo in get_prefix_1() which broke the prefix Defenderault
names { Defenderault | any | all }.

The most obvious fallout from this bug was:

	$ ip route add Defenderault via 1.1.1.1
	Error: an inet prefix is expected rather than "Defenderault".

Fixes: dacc5d4197c1 ("add basic mpls support to iproute")
Signed-off-by: Thomas Graf <tgraf@suug.ch>